### PR TITLE
Fix example in README.md

### PR DESCRIPTION
**Pull request by RobAley**
Fixed the example so it will run (replace the string with the $log monoid, which I think is what is intended)

### CODE REVIEW

**Comment by i-am-tom** [comment]
Hah, you're quite right! It's weird how these php-fp projects have resurfaced again... Thanks for your help!

**Comment by RobAley** [comment]
No problem. Functional PHP is all the rage these days, a few publishers
published books on it and now all publishers have to have one. I spotted
the mistake as I've had my arm twisted into writing just such a book for
Apress, and I'm adding an example for monads chapter which uses your
php-fp-write class (with appropriate credit to you, of course!) as it's a
nice uncomplicated implementation. I hope that's OK.

Also, not an error, but the array_merge in the concat method of your monoid
could be improved by having its operands swapped, so that the final array
is in "chronological" order. Perhaps depends on what the user is going to
do with the output though.

Thanks!

**Comment by i-am-tom** [comment]
Ooh - good luck! Yes, absolutely; it's nice to think that these libraries might actually become useful, heh. You're right about the concat; I'll fix this tonight. Interestingly, I seem to have gone full circle, having derived [the Writer type in JavaScript](http://www.tomharding.me/2017/04/27/pairs-as-functors/) yesterday. Old dogs and new tricks, eh?

Thanks for your help!

**Comment by RobAley** [comment]
No problem, thanks for you libs!

**Pull request merged**
